In [63]:
import pandas as pd
import numpy as np
import csv

In [84]:
def readDataFromCSV(filename):
    dict_list = []
    reader = csv.DictReader(open(filename, 'rb'))
    for line in reader:
        dict_list.append(line)
    return dict_list

ant_pers = pd.read_csv('ant_pers.csv')
ant_pers.set_index('an_folio')

vant_pers = ant_pers.values
snps = readDataFromCSV('snps.csv')

          Obesidad
an_folio
1                1
2                0
3                1
4                1
5                0
6                0
7                0
8                0
9                0
10               0
11               0
12               0
13               1
14               0
15               0
17               1
18               0
19               0
20               0
21               1
22               0
23               0
24               0
25               1
26               0
27               0
28               0
29               0
30               0
31               0
...            ...
1051             0
1052             0
1053             1
1054             0
1055             0
1056             0
1057             0
1058             0
1059             1
1060             0
1061             1
1062             0
1063             0
1064             0
1065             0
1066             0
1067             0
1068             1
1069             0
1070             0
1071             1
1072             0
1073             0
1074             0
1075             0
1076             1
1077             0
1078             0
1079             0
1080             0

[1076 rows x 1 columns]

In [ ]:
for i in range(ant_pers.shape[0]):